server:
  port: 8080
spring:
  application:
    name: utilities
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        generate_statistics: true
  datasource:
    platform: hsqldb
    url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
    username: hsqldb
    password: hsqldb
    driverClassName: org.hsqldb.jdbc.JDBCDriver